import { query } from './pool';

const seedData = {
  brands: [
    { name: 'Maruti Suzuki', logo_url: 'https://via.placeholder.com/100?text=Maruti', country: 'India', website: 'https://maruti.co.in' },
    { name: 'Hyundai', logo_url: 'https://via.placeholder.com/100?text=Hyundai', country: 'South Korea', website: 'https://hyundai.co.in' },
    { name: 'Tata Motors', logo_url: 'https://via.placeholder.com/100?text=Tata', country: 'India', website: 'https://tatamotors.com' },
    { name: 'Mahindra', logo_url: 'https://via.placeholder.com/100?text=Mahindra', country: 'India', website: 'https://mahindra.com' },
    { name: 'Honda', logo_url: 'https://via.placeholder.com/100?text=Honda', country: 'Japan', website: 'https://honda.co.in' },
    { name: 'Toyota', logo_url: 'https://via.placeholder.com/100?text=Toyota', country: 'Japan', website: 'https://toyota.co.in' },
    { name: 'Kia', logo_url: 'https://via.placeholder.com/100?text=Kia', country: 'South Korea', website: 'https://kia.co.in' },
    { name: 'Volkswagen', logo_url: 'https://via.placeholder.com/100?text=VW', country: 'Germany', website: 'https://volkswagen.co.in' },
    { name: 'Skoda', logo_url: 'https://via.placeholder.com/100?text=Skoda', country: 'Czech Republic', website: 'https://skoda.co.in' },
    { name: 'MG Motor', logo_url: 'https://via.placeholder.com/100?text=MG', country: 'China', website: 'https://mgmotors.co.in' },
  ],
  vehicles: [
    {
      brandIndex: 0,
      name: 'Swift',
      category: 'Hatchback',
      fuelType: 'Petrol',
      transmission: 'Manual',
      bodyType: 'Hatchback',
      seatCapacity: 5,
      engineDisplacement: 1197,
      maxPower: '82 bhp',
      maxTorque: '113 Nm',
      mileage: '23.2 km/l',
      acceleration: '10.2 seconds',
      topSpeed: '180 km/h',
      weight: 860,
      dimensions: '3840 x 1735 x 1500 mm',
      bootSpace: 268,
      tankCapacity: 42,
      groundClearance: '170 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/100,000 km',
      price: 550000,
      image: 'https://via.placeholder.com/500x300?text=Maruti+Swift',
    },
    {
      brandIndex: 0,
      name: 'Ertiga',
      category: 'MPV',
      fuelType: 'Petrol',
      transmission: 'Manual',
      bodyType: 'MPV',
      seatCapacity: 7,
      engineDisplacement: 1462,
      maxPower: '103 bhp',
      maxTorque: '138 Nm',
      mileage: '20.5 km/l',
      acceleration: '12.5 seconds',
      topSpeed: '175 km/h',
      weight: 1150,
      dimensions: '4270 x 1735 x 1665 mm',
      bootSpace: 225,
      tankCapacity: 50,
      groundClearance: '185 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/100,000 km',
      price: 750000,
      image: 'https://via.placeholder.com/500x300?text=Maruti+Ertiga',
    },
    {
      brandIndex: 1,
      name: 'Creta',
      category: 'SUV',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      bodyType: 'SUV',
      seatCapacity: 5,
      engineDisplacement: 1497,
      maxPower: '113 bhp',
      maxTorque: '144 Nm',
      mileage: '17.5 km/l',
      acceleration: '10.8 seconds',
      topSpeed: '180 km/h',
      weight: 1255,
      dimensions: '4300 x 1790 x 1635 mm',
      bootSpace: 440,
      tankCapacity: 50,
      groundClearance: '200 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/100,000 km',
      price: 1000000,
      image: 'https://via.placeholder.com/500x300?text=Hyundai+Creta',
    },
    {
      brandIndex: 1,
      name: 'i20',
      category: 'Hatchback',
      fuelType: 'Petrol',
      transmission: 'Manual',
      bodyType: 'Hatchback',
      seatCapacity: 5,
      engineDisplacement: 1197,
      maxPower: '82 bhp',
      maxTorque: '115 Nm',
      mileage: '23 km/l',
      acceleration: '10.5 seconds',
      topSpeed: '180 km/h',
      weight: 1050,
      dimensions: '3995 x 1775 x 1505 mm',
      bootSpace: 311,
      tankCapacity: 37,
      groundClearance: '185 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/100,000 km',
      price: 600000,
      image: 'https://via.placeholder.com/500x300?text=Hyundai+i20',
    },
    {
      brandIndex: 2,
      name: 'Nexon',
      category: 'SUV',
      fuelType: 'Diesel',
      transmission: 'Manual',
      bodyType: 'SUV',
      seatCapacity: 5,
      engineDisplacement: 1497,
      maxPower: '110 bhp',
      maxTorque: '260 Nm',
      mileage: '21.5 km/l',
      acceleration: '12.3 seconds',
      topSpeed: '175 km/h',
      weight: 1200,
      dimensions: '3995 x 1790 x 1605 mm',
      bootSpace: 350,
      tankCapacity: 50,
      groundClearance: '200 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/150,000 km',
      price: 850000,
      image: 'https://via.placeholder.com/500x300?text=Tata+Nexon',
    },
    {
      brandIndex: 2,
      name: 'Harrier',
      category: 'SUV',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      bodyType: 'SUV',
      seatCapacity: 5,
      engineDisplacement: 1956,
      maxPower: '170 bhp',
      maxTorque: '350 Nm',
      mileage: '16 km/l',
      acceleration: '9.8 seconds',
      topSpeed: '190 km/h',
      weight: 1600,
      dimensions: '4598 x 1894 x 1706 mm',
      bootSpace: 656,
      tankCapacity: 60,
      groundClearance: '200 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/150,000 km',
      price: 1450000,
      image: 'https://via.placeholder.com/500x300?text=Tata+Harrier',
    },
    {
      brandIndex: 3,
      name: 'XUV500',
      category: 'SUV',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      bodyType: 'SUV',
      seatCapacity: 5,
      engineDisplacement: 2200,
      maxPower: '190 bhp',
      maxTorque: '350 Nm',
      mileage: '15.3 km/l',
      acceleration: '9.2 seconds',
      topSpeed: '190 km/h',
      weight: 1765,
      dimensions: '4600 x 1890 x 1755 mm',
      bootSpace: 600,
      tankCapacity: 60,
      groundClearance: '210 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/150,000 km',
      price: 1850000,
      image: 'https://via.placeholder.com/500x300?text=Mahindra+XUV500',
    },
    {
      brandIndex: 4,
      name: 'City',
      category: 'Sedan',
      fuelType: 'Petrol',
      transmission: 'Manual',
      bodyType: 'Sedan',
      seatCapacity: 5,
      engineDisplacement: 1198,
      maxPower: '90 bhp',
      maxTorque: '110 Nm',
      mileage: '23.8 km/l',
      acceleration: '11.3 seconds',
      topSpeed: '180 km/h',
      weight: 1055,
      dimensions: '4445 x 1748 x 1475 mm',
      bootSpace: 506,
      tankCapacity: 50,
      groundClearance: '170 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/100,000 km',
      price: 1100000,
      image: 'https://via.placeholder.com/500x300?text=Honda+City',
    },
    {
      brandIndex: 5,
      name: 'Fortuner',
      category: 'SUV',
      fuelType: 'Diesel',
      transmission: 'Manual',
      bodyType: 'SUV',
      seatCapacity: 7,
      engineDisplacement: 2393,
      maxPower: '150 bhp',
      maxTorque: '343 Nm',
      mileage: '13.5 km/l',
      acceleration: '11.6 seconds',
      topSpeed: '180 km/h',
      weight: 2750,
      dimensions: '4795 x 1855 x 1835 mm',
      bootSpace: 200,
      tankCapacity: 80,
      groundClearance: '225 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '5 years/150,000 km',
      price: 2850000,
      image: 'https://via.placeholder.com/500x300?text=Toyota+Fortuner',
    },
    {
      brandIndex: 6,
      name: 'Seltos',
      category: 'SUV',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      bodyType: 'SUV',
      seatCapacity: 5,
      engineDisplacement: 1598,
      maxPower: '115 bhp',
      maxTorque: '151 Nm',
      mileage: '17.6 km/l',
      acceleration: '11.2 seconds',
      topSpeed: '180 km/h',
      weight: 1275,
      dimensions: '4315 x 1800 x 1635 mm',
      bootSpace: 433,
      tankCapacity: 50,
      groundClearance: '200 mm',
      warrantyBasic: '3 years/100,000 km',
      warrantyPowertrain: '7 years/160,000 km',
      price: 1050000,
      image: 'https://via.placeholder.com/500x300?text=Kia+Seltos',
    },
  ],
};

export const seedDatabase = async () => {
  try {
    console.log('Seeding database with sample data...');

    // Seed brands
    for (const brand of seedData.brands) {
      await query(
        `INSERT INTO brands (name, logo_url, country, website) VALUES ($1, $2, $3, $4) ON CONFLICT (name) DO NOTHING`,
        [brand.name, brand.logo_url, brand.country, brand.website]
      );
    }

    // Get brand IDs
    const brandResult = await query('SELECT id, name FROM brands');
    const brandMap: { [key: string]: number } = {};
    brandResult.rows.forEach((row: any) => {
      brandMap[row.name] = row.id;
    });

    // Seed vehicles
    for (const vehicle of seedData.vehicles) {
      const brandId = brandMap[seedData.brands[vehicle.brandIndex].name];
      const slug = vehicle.name.toLowerCase().replace(/\s+/g, '-');

      await query(
        `INSERT INTO vehicles (
          brand_id, name, slug, category, fuel_type, transmission, body_type,
          seating_capacity, engine_displacement, max_power, max_torque, mileage,
          acceleration_0_100, top_speed, weight, dimensions, boot_space, tank_capacity,
          ground_clearance, warranty_basic, warranty_powertrain, image_url, starting_price
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
        ON CONFLICT (slug) DO NOTHING`,
        [
          brandId, vehicle.name, slug, vehicle.category, vehicle.fuelType, vehicle.transmission,
          vehicle.bodyType, vehicle.seatCapacity, vehicle.engineDisplacement, vehicle.maxPower,
          vehicle.maxTorque, vehicle.mileage, vehicle.acceleration, vehicle.topSpeed, vehicle.weight,
          vehicle.dimensions, vehicle.bootSpace, vehicle.tankCapacity, vehicle.groundClearance,
          vehicle.warrantyBasic, vehicle.warrantyPowertrain, vehicle.image, vehicle.price,
        ]
      );
    }

    console.log('Database seeded successfully');
  } catch (error) {
    console.error('Error seeding database:', error);
    throw error;
  }
};
